package:
  name: imread
  version: !!str 0.4

source:
  git_url: git://github.com/luispedro/imread.git
  git_tag: release-0.4

#  patches:
   # List any patch files here
   # - fix.patch


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - imread


  requires:
    - nose
    - scipy

about:
  home: http://imread.rtfd.org/
  license: MIT License
  summary: 'imread: Image reading library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
